#!/usr/bin/env bash


declare -rx PARAMS_SCRIPT="${PARAMS_SCRIPT:-}"
declare -rx PARAMS_VERSION="${PARAMS_VERSION:-}"

declare -rx WORKSPACES_MANIFEST_DIR_PATH="${WORKSPACES_MANIFEST_DIR_PATH:-}"
declare -rx WORKSPACES_MANIFEST_DIR_BOUND="${WORKSPACES_MANIFEST_DIR_BOUND:-}"
declare -rx WORKSPACES_KUBECONFIG_DIR_PATH="${WORKSPACES_KUBECONFIG_DIR_PATH:-}"
declare -rx WORKSPACES_KUBECONFIG_DIR_BOUND="${WORKSPACES_KUBECONFIG_DIR_BOUND:-}"

#
# Asserting Environment
#

exported_or_fail \
    WORKSPACES_MANIFEST_DIR_PATH \
    WORKSPACES_KUBECONFIG_DIR_PATH \
    PARAMS_SCRIPT \
    PARAMS_VERSION
